### ISSUE TITLE
Audio is gone after PC shuts down

### ISSUE THREAD

**Issue by EchoRoblox** [crash5band/MikuMikuWorld#1]
This is an issue I found with the audio. Sometimes I chart to the extent of forgetting to shut down my PC properly.

Therefore after rebooting the PC, the audio is gone. I can only solve the problem by closing and reopening the MMW charter.

Is it possible so that this doesn’t happen? Thank you for reading.

**Comment by crash5band** [comment]
I haven't run into this and was not able to replicate it but I was thinking it might be due to miniaudio not shutting down and releasing the audio device properly so I made sure the application does so now. I don't know if this will fix it but you can try updating to the latest version from here:
https://github.com/crash5band/MikuMikuWorld/releases/tag/v1.2.0

I'll keep this open for now so let me know if the issue is resolved.

**Comment by EchoRoblox** [comment]
It is fixed now, thank you.
