### ISSUE TITLE
Feature Request: No fade option on guides

### ISSUE THREAD

**Issue by Lorekeeper49** [crash5band/MikuMikuWorld#72]
I know there are official charts where some guides don't fade and I recently found out that they use the same note type they use for skills to make that work, they just place it on the guide.  So, could you please add a no fade option to guides, and while you're at it, maybe figure fade in too because I swear I remember some official charts having guides fade in.

**Comment by crash5band** [comment]
I won't be adding no fade options because it is not supported by the game. There are no notes used by the game to achieve a no fade effect. In the official charts however, they control the amount of fade-out by adding slide step notes near the end of the guide.

Example in アイムマイン:
![im_mine_guide_fade_control](https://github.com/user-attachments/assets/ca67a2be-2a93-4cfa-a053-7c2b5deb6b39)

**Comment by Lorekeeper49** [comment]
> I won't be adding no fade options because it is not supported by the game. There are no notes used by the game to achieve a no fade effect. In the official charts however, they control the amount of fade-out by adding slide step notes near the end of the guide.
> 
> Example in アイムマイン:
> ![im_mine_guide_fade_control](https://github.com/user-attachments/assets/ca67a2be-2a93-4cfa-a053-7c2b5deb6b39)

Oh, okay, I didn't realize
